# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bank_cards_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankcards_db
    ports:
      - "5432:5432"
