#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: a465a9bf0140a181a6a85da5358dd7c47aaaa610901bdbb9a02d64d06fa1eb26
    expirationMs: 3600000

  encryptor:
    secret: v5Eddb6esvVQ05sPPJ1kZWOAdTxRiQj7LYCKEmamvr0=
