
create table block_card_operations (
    card_id bigint not null,
    id bigint not null,
    primary key (id)
);

create table card_operations (
    id bigint generated by default as identity,
    user_id bigint not null,
    status varchar(255) not null check (status in ('PENDING','COMPLETED','CANCELED')),
    primary key (id)
);

create table cards (
    balance numeric(38,2),
    expiration_date date not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    masked_number varchar(255) not null,
    number varchar(255) not null,
    status varchar(255) not null check (status in ('ACTIVE','BLOCKED','EXPIRED')),
    primary key (id)
);

create table roles (
    id bigint generated by default as identity,
    name varchar(255) not null check (name in ('ROLE_USER','ROLE_ADMIN')),
    primary key (id)
);

create table transactions (
    monetary_amount numeric(38,2) not null,
    destination_card_id bigint not null,
    id bigint generated by default as identity,
    source_card_id bigint not null,
    user_id bigint not null,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    role_id bigint not null,
    password varchar(255) not null,
    phone_number varchar(255) not null unique,
    primary key (id)
);

alter table if exists block_card_operations
   add constraint FK7kahlscvlvalg159jblb7hnc2
   foreign key (card_id)
   references cards;

alter table if exists block_card_operations
   add constraint FKdc0grbg0ux9r8q078bstfp4bc
   foreign key (id)
   references card_operations;

alter table if exists card_operations
   add constraint FK2wukw0xqvyuxvbwk1wc2vkryo
   foreign key (user_id)
   references users;

alter table if exists cards
   add constraint FKcmanafgwbibfijy2o5isfk3d5
   foreign key (user_id)
   references users;

alter table if exists transactions
   add constraint FKl65hx5ap6gd114pr5gmvo796r
   foreign key (destination_card_id)
   references cards;

alter table if exists transactions
   add constraint FKbqcjg4djqerhkov0me35sqnsv
   foreign key (source_card_id)
   references cards;

alter table if exists transactions
   add constraint FKqwv7rmvc8va8rep7piikrojds
   foreign key (user_id)
   references users;

alter table if exists users
   add constraint FKp56c1712k691lhsyewcssf40f
   foreign key (role_id)
   references roles;